Repository cloudfoundry/cf-deployment, pull requests merged in 2018-07, with the labels that each got.

#537 Add UAA TLS
  operations/experimental/migrate-cf-mysql-to-pxc.yml
  operations/experimental/use-pxc.yml
Labels: in progress

#541 Place the ca_certs property in the tls namespace
  operations/experimental/perm-service.yml
Labels: in progress

#554 Override default deployment name in uaa dns alias.
  operations/use-bosh-dns-rename-network-and-deployment.yml
Labels: in progress

#552 mysql proxy job uses regular consul service discovery
  cf-deployment.yml
  operations/experimental/disable-consul.yml
  operations/experimental/migrate-cf-mysql-to-pxc.yml
  operations/experimental/use-pxc.yml
Labels: in progress

#543 Add key_properties nested hash to cf-deployment ops file
  operations/experimental/secure-service-credentials.yml
Labels: in progress

#549 Update README.md
  iaas-support/bosh-lite/README.md
Labels: scheduled

#532 Add support for alicloud blobstore
  iaas-support/alicloud/stemcells.yml
  operations/README.md
  operations/example-vars-files/vars-use-alicloud-oss-blobstore.yml
  operations/use-alicloud-oss-blobstore.yml
  scripts/test-standard-ops.sh
Labels: in progress

#558 Balance quotes in docs
  operations/README.md
Labels: in progress

#559 please upgrade datadog nozzle version away from cf-attic
  operations/test/add-datadog-firehose-nozzle.yml
Labels: in progress

#533 Add cf networking components to pxc opsfiles
  operations/experimental/migrate-cf-mysql-to-pxc.yml
  operations/experimental/use-pxc.yml
Labels: in progress

#557 Experimentally enable BPM for Garden
  operations/experimental/enable-bpm.yml
Labels: in progress

#560 Upgrade pxc to 0.11.0
  operations/experimental/migrate-cf-mysql-to-pxc.yml
  operations/experimental/use-pxc.yml
Labels: in progress

#561 Add cc.database_encryption properties to Cloud Controller jobs
  cf-deployment.yml
Labels: scheduled

#544 **BREAKING**: Improve syslog vars
  operations/addons/enable-component-syslog.yml
  operations/addons/example-vars-files/vars-enable-component-syslog.yml
Labels: scheduled, v3

#535 Log cache promote
  cf-deployment.yml
  operations/README.md
  operations/disable-log-cache.yml
  operations/experimental/README.md
  operations/experimental/use-log-cache.yml
  scripts/semantic-tests.sh
  scripts/test-experimental-ops.sh
  scripts/test-standard-ops.sh
Labels: in progress

#506 Enables BPM for Cloud Controller jobs
  operations/experimental/enable-bpm.yml
Labels: in progress
