Repository cloudfoundry/cf-deployment, pull requests merged in 2018-03, with the labels that each got.

#421 Drop deprecated `use_v2_tls` property on rep
  cf-deployment.yml
Labels: scheduled

#412 Removing unused variables when using an external db
  operations/use-external-dbs.yml
  scripts/fixtures/test-base-vars-store.yml
Labels: in progress

#427 bbl create-lbs is not a valid command
  deployment-guide.md
Labels: in progress

#436 Use loggregator v2 api on windows2016
  operations/experimental/windows2016-cell.yml
Labels: in progress

#430 Removes duplicate entry
  operations/experimental/README.md
Labels: unscheduled

#433 Configure ssh_proxy on BOSH-Lite to skip consul
  operations/experimental/disable-consul-bosh-lite.yml
Labels: in progress

#426 Add ops file for enabling istio release
  operations/experimental/README.md
  operations/experimental/add-istio-release.yml
  scripts/test-experimental-ops.sh
Labels: scheduled

#439 Fix env vars in upload-stemcell command
  deployment-guide.md
Labels: scheduled

#440 add fast-deploy-with-downtime-and-danger.yml for impatient developers
  operations/experimental/README.md
  operations/experimental/fast-deploy-with-downtime-and-danger.yml
  scripts/test-experimental-ops.sh
Labels: in progress

#443 Explicitly set default grootfs GC property
  cf-deployment.yml
Labels: in progress

#417 Bump bpm-release to 0.3.0
  operations/experimental/enable-bpm.yml
Labels: scheduled

#422 Promote windows2016 opsfiles out of experimental
  operations/README.md
  operations/experimental/README.md
  operations/use-latest-windows2016-stemcell.yml
  operations/use-offline-windows2016fs.yml
  operations/windows2016-cell.yml
  scripts/test-experimental-ops.sh
  scripts/test-standard-ops.sh
Labels: scheduled
