Repository cloudfoundry/cf-deployment, pull requests merged in 2018-05, with the labels that each got.

#465 operations: Custom S3 provider for blobstore
  operations/README.md
  operations/example-vars-files/vars-use-s3-custom-blobstore.yml
  operations/use-s3-custom-blobstore.yml
  scripts/test-standard-ops.sh
Labels: in progress

#476 pxc proxy dashboard and credhub fix
  operations/experimental/migrate-cf-mysql-to-pxc.yml
  operations/experimental/use-pxc.yml
Labels: in progress

#481 Add new required encryption_keys property to uaa job
  cf-deployment.yml
Labels: in progress

#482 Allow bits-service.* and bits.* for Bits-Service certificate
  operations/experimental/bits-service.yml
Labels: in progress

#483 Move bits-service into a separate VM
  operations/experimental/bits-service-local.yml
  operations/experimental/bits-service-s3.yml
  operations/experimental/bits-service-webdav.yml
  operations/experimental/bits-service.yml
  operations/experimental/enable-bits-service-consul.yml
  operations/experimental/use-bosh-dns-rename-network-and-deployment.yml
  operations/experimental/use-bosh-dns.yml
Labels: in progress

#490 Update use-log-cache.yml to collocate log-cache on doppler vms
  operations/experimental/use-log-cache.yml
  scripts/semantic-tests.sh
Labels: in progress

#498 Add perm.admin scope to the CF CLI admin user
  cf-deployment.yml
  operations/experimental/perm-service.yml
Labels: in progress

#497 Bumped perm to version 0.0.7
  operations/experimental/perm-service.yml
Labels: in progress

#502 Add db tls for pxc
  operations/experimental/migrate-cf-mysql-to-pxc.yml
  operations/experimental/use-pxc.yml
Labels: in progress

#501 Bump pxc release to 0.6.0 in migration ops file
  operations/experimental/migrate-cf-mysql-to-pxc.yml
Labels: scheduled

#505 Update pxc database ports to match cf-mysql port
  operations/experimental/use-pxc.yml
Labels: unscheduled

#509 Include required mapfs job in enable nfs-volume-service.yml
  operations/enable-nfs-volume-service.yml
Labels: in progress

#508 Rename URLs from bits-service.* to bits.*
  operations/experimental/bits-service.yml
  operations/experimental/enable-bits-service-consul.yml
  operations/experimental/use-bosh-dns-rename-network-and-deployment.yml
  operations/experimental/use-bosh-dns.yml
Labels: in progress

#513 Allow garden to use containerd
  operations/experimental/README.md
  operations/experimental/use-garden-containerd.yml
  scripts/test-experimental-ops.sh
Labels: in progress
