Repository cloudfoundry/cf-deployment, pull requests merged in 2018-11, with the labels that each got.

#640 Update enable_bpm_garden
  operations/experimental/enable-bpm-garden.yml
Labels: in progress

#636 PR: Remove bpm.enabled property [#160864383]
  cf-deployment.yml
Labels: in progress

#646 Add expvar forwarder job to loggregator-agent addon
  cf-deployment.yml
Labels: in progress

#655 Add opsfile to enable backup/restore for gcs blobstore
  operations/backup-and-restore/README.md
  operations/backup-and-restore/enable-backup-restore-gcs.yml
  operations/backup-and-restore/example-vars-files/vars-enable-backup-restore-gcs.yml
  scripts/test-backup-and-restore.sh
Labels: in progress

#654 Remove persistent_image_list property
  cf-deployment.yml
  operations/test/add-persistent-isolation-segment-diego-cell.yml
Labels: in progress

#656 Use Client Credentials in nfsbrokerpush Errand
  operations/enable-nfs-volume-service.yml
Labels: scheduled

#666 The binary buildpack does not get compiled on Windows vms
  operations/experimental/use-compiled-releases-windows.yml
Labels: in progress

#665 Deprecate enable-backup-restore-smb-broker.yml ops-file
  operations/backup-and-restore/README.md
  operations/backup-and-restore/enable-backup-restore-smb-broker.yml
Labels: in progress

#664 Default experimental_containerd_mode to true
  cf-deployment.yml
  operations/experimental/README.md
  operations/experimental/enable-bpm-garden.yml
  operations/experimental/rootless-containers.yml
  operations/experimental/use-garden-containerd.yml
  operations/experimental/use-native-garden-runc-runner.yml
  operations/test/add-persistent-isolation-segment-diego-cell.yml
  scripts/test-experimental.sh
Labels: in progress

#668 Add experimental opsfiles to enable route integrity on windows1803 and window2016
  operations/experimental/README.md
  operations/experimental/enable-routing-integrity-windows1803.yml
  operations/experimental/enable-routing-integrity-windows2016.yml
  scripts/test-experimental.sh
Labels: in progress

#624 Loggregator iso segments
  interpolated
  operations/test/add-persistent-isolation-segment-infrastructure-metrics.yml
  operations/test/add-persistent-isolation-segment-logging-system.yml
  operations/test/add-persistent-isolation-segment-syslog-drain.yml
  operations/test/alter-router-for-log-agent.yml
  scripts/test-test.sh
Labels: in progress

#670 Upgrade Log Cache to v2.0.2 and fix certificates
  cf-deployment.yml
Labels: in progress

#671 Remove obsolete property router.backends.enable_tls
  cf-deployment.yml
Labels: scheduled

#653 operations/deploy-forwarder-agent:
  operations/experimental/README.md
  operations/experimental/deploy-forwarder-agent.yml
  scripts/test-experimental.sh
Labels: unscheduled
