Repository cloudfoundry/cf-deployment, pull requests merged in 2019-07, with the labels that each got.

#746 inlined enable-routing-integrity.yml into cf-deployment.yml
  cf-deployment.yml
  operations/README.md
  operations/enable-routing-integrity.yml
Labels: in progress

#793 Change instructions in PR template
  PULL_REQUEST_TEMPLATE.md
Labels: unscheduled

#792 Add ops-file for enabling route integrity with nginx on windows 2019.
  operations/experimental/README.md
  operations/experimental/enable-nginx-routing-integrity-windows2019.yml
  scripts/test-experimental.sh
  units/tests/experimental_test/operations_test.go
Labels: in progress

#786 Disable uaa legacy redirect uri matching
  operations/experimental/README.md
  operations/experimental/disable-uaa-client-redirect-uri-legacy-matching-mode.yml
  scripts/test-experimental.sh
  units/tests/experimental_test/operations_test.go
Labels: in progress

#789 add set-cpu-weight yml files to windows1803 and windows2019
  operations/experimental/README.md
  operations/experimental/set-cpu-weight-windows1803.yml
  operations/experimental/set-cpu-weight-windows2019.yml
  scripts/test-experimental.sh
  units/tests/experimental_test/operations_test.go
Labels: in progress

#791 Internal Markdown links resolve correctly on GitHub
  texts/deployment-guide.md
  texts/on-cloud-configs.md
Labels: scheduled

#796 Add opsfile to use offline windowsfs-releases
  operations/README.md
  operations/use-offline-windows1803fs.yml
  operations/use-offline-windows2019fs.yml
  scripts/test-operations.sh
  units/tests/standard_test/operations_test.go
Labels: scheduled

#803 remove unused metrics_urls property from prom_scraper
  cf-deployment.yml
  operations/experimental/add-metric-store.yml
  operations/test/add-persistent-isolation-segment-logging-system.yml
  operations/windows1803-cell.yml
  operations/windows2019-cell.yml
Labels: scheduled
