Repository cloudfoundry/cf-deployment, pull requests merged in 2020-07, with the labels that each got.

#892 feat: enable service-discovery by default
  cf-deployment.yml
  operations/enable-service-discovery.yml
Labels: in progress

#889 Add CN to SAN for logcache syslog-server
  operations/experimental/use-logcache-syslog-ingress.yml
Labels: scheduled

#894 Add ops file allowing operators to disable the v2 CC API
  operations/experimental/README.md
  operations/experimental/disable-v2-api.yml
  units/tests/experimental_test/operations.yml
Labels: unscheduled

#895 set ssl-strict-internal to true for use-logcache ops files
  operations/experimental/use-logcache-syslog-ingress-windows2019.yml
  operations/experimental/use-logcache-syslog-ingress.yml
Labels: scheduled

#896 Update cf smoke tests release 41.0.0
  cf-deployment.yml
Labels: in progress
