Repository cloudfoundry/cf-deployment, pull requests merged in 2020-03, with the labels that each got.

#868 Add the disabled syslog agent ops file
  ci/pipelines/cf-deployment.yml
  operations/experimental/README.md
  operations/experimental/add-disabled-syslog-agent-for-upgrade.yml
  units/tests/experimental_test/operations.yml
Labels: in progress

#871 Update metric store release 1.3.0
  operations/use-metric-store.yml
Labels: in progress

#874 Add an ops-file to colocate smoke-tests on cc-worker
  operations/experimental/README.md
  operations/experimental/colocate-smoke-tests-on-cc-worker.yml
  units/tests/experimental_test/operations.yml
Labels: scheduled

#872 Remove unused variable cf_bosh_password
  cf-deployment.yml
  scripts/fixtures/unit-test-vars-store.yml
Labels: scheduled

#875 Revert "Remove unused variable cf_bosh_password"
  cf-deployment.yml
  scripts/fixtures/unit-test-vars-store.yml
Labels: unscheduled
