Repository cloudfoundry/cf-deployment, pull requests merged in 2020-04, with the labels that each got.

#876 Add enable-direct-io-grootfs experimental flag
  operations/experimental/README.md
  operations/experimental/enable-direct-io-grootfs.yml
  units/tests/experimental_test/operations.yml
Labels: accepted

#877 Enhancement: NATS servers are now addressed with hostnames instead of IP addresses
  cf-deployment.yml
Labels: unscheduled

#873 allow api and worker instance groups to deploy in parallel
  cf-deployment.yml
  operations/experimental/fast-deploy-with-downtime-and-danger.yml
Labels: scheduled

#867 Default to syslog agents and remove syslog adapters
  cf-deployment.yml
  operations/README.md
  operations/bosh-lite.yml
  operations/cf-syslog-skip-cert-verify.yml
  operations/experimental/README.md
  operations/experimental/add-syslog-agent-windows1803.yml
  operations/experimental/add-syslog-agent-windows2019.yml
  operations/experimental/add-syslog-agent.yml
  operations/experimental/use-logcache-syslog-ingress-windows2019.yml
  operations/rename-network-and-deployment.yml
  operations/scale-to-one-az.yml
  operations/use-compiled-releases.yml
  operations/windows1803-cell.yml
  operations/windows2019-cell.yml
  units/tests/standard_test/operations.yml
Labels: in progress

#841 Remove experimental ops file that is unused by UAA.
  operations/experimental/README.md
  operations/experimental/disable-uaa-client-redirect-uri-legacy-matching-mode.yml
  units/tests/experimental_test/operations.yml
Labels: in progress

#879 supplemental updates to cf-deployment for loggregator-agent 6.0.0
  operations/experimental/README.md
  operations/experimental/disable-logs-in-firehose-windows2019.yml
  operations/experimental/disable-logs-in-firehose.yml
  operations/experimental/use-logcache-syslog-ingress-windows2019.yml
  operations/experimental/use-logcache-syslog-ingress.yml
  units/tests/experimental_test/operations.yml
Labels: in progress

#855 Optimize deployment parallelization
  cf-deployment.yml
  operations/experimental/fast-deploy-with-downtime-and-danger.yml
Labels: in progress
